//
// InlineResponse20014Areacodes.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class InlineResponse20014Areacodes: JSONEncodable {
    public var countryCode: String?
    public var stateId: Int32?
    public var areaCode: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["country_code"] = self.countryCode
        nillableDictionary["state_id"] = self.stateId?.encodeToJSON()
        nillableDictionary["area_code"] = self.areaCode
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
