//
// InlineResponse2003Created.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class InlineResponse2003Created: JSONEncodable {
    public var date: NSDate?
    public var timezoneType: Int32?
    public var timezone: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["date"] = self.date?.encodeToJSON()
        nillableDictionary["timezone_type"] = self.timezoneType?.encodeToJSON()
        nillableDictionary["timezone"] = self.timezone
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
