//
// InlineResponse2004MetaPagination.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The pagination data */
public class InlineResponse2004MetaPagination: JSONEncodable {
    public var total: Int32?
    public var count: Int32?
    public var perPage: Int32?
    public var currentPage: Int32?
    public var totalPages: Int32?
    public var links: InlineResponse2004MetaPaginationLinks?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["total"] = self.total?.encodeToJSON()
        nillableDictionary["count"] = self.count?.encodeToJSON()
        nillableDictionary["per_page"] = self.perPage?.encodeToJSON()
        nillableDictionary["current_page"] = self.currentPage?.encodeToJSON()
        nillableDictionary["total_pages"] = self.totalPages?.encodeToJSON()
        nillableDictionary["links"] = self.links?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
