//
// InlineResponse20016Data.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class InlineResponse20016Data: JSONEncodable {
    public var id: Int32?
    public var didId: Int32?
    public var didGroupId: Int32?
    public var countryCode: String?
    public var cityName: String?
    public var areaCode: String?
    public var number: String?
    public var type: String?
    public var trunkId: Int32?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id?.encodeToJSON()
        nillableDictionary["did_id"] = self.didId?.encodeToJSON()
        nillableDictionary["did_group_id"] = self.didGroupId?.encodeToJSON()
        nillableDictionary["country_code"] = self.countryCode
        nillableDictionary["city_name"] = self.cityName
        nillableDictionary["area_code"] = self.areaCode
        nillableDictionary["number"] = self.number
        nillableDictionary["type"] = self.type
        nillableDictionary["trunk_id"] = self.trunkId?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
