//
// InlineResponse20017Numbers.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class InlineResponse20017Numbers: JSONEncodable {
    public var id: Int32?
    public var orderReference: String?
    public var countryCode: String?
    public var country: String?
    public var cityName: String?
    public var areaCode: String?
    public var didGroupId: Int32?
    public var didNumber: String?
    public var expirationDate: ISOFullDate?
    public var status: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id?.encodeToJSON()
        nillableDictionary["order_reference"] = self.orderReference
        nillableDictionary["country_code"] = self.countryCode
        nillableDictionary["country"] = self.country
        nillableDictionary["city_name"] = self.cityName
        nillableDictionary["area_code"] = self.areaCode
        nillableDictionary["did_group_id"] = self.didGroupId?.encodeToJSON()
        nillableDictionary["did_number"] = self.didNumber
        nillableDictionary["expiration_date"] = self.expirationDate?.encodeToJSON()
        nillableDictionary["status"] = self.status
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
