//
// InlineResponse20012Data.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class InlineResponse20012Data: JSONEncodable {
    public var country: String?
    public var slug: String?
    public var a2Code: String?
    public var dialCode: Int32?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["country"] = self.country
        nillableDictionary["slug"] = self.slug
        nillableDictionary["a2_code"] = self.a2Code
        nillableDictionary["dial_code"] = self.dialCode?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
