//
// InlineResponse2004Inbox.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class InlineResponse2004Inbox: JSONEncodable {
    public var id: Int32?
    public var didId: Int32?
    public var filename: String?
    public var filesize: String?
    public var number: String?
    public var sender: String?
    public var totalPages: Int32?
    public var createdAt: InlineResponse2003Created?
    public var previewFile: String?
    public var fileUrl: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id?.encodeToJSON()
        nillableDictionary["did_id"] = self.didId?.encodeToJSON()
        nillableDictionary["filename"] = self.filename
        nillableDictionary["filesize"] = self.filesize
        nillableDictionary["number"] = self.number
        nillableDictionary["sender"] = self.sender
        nillableDictionary["total_pages"] = self.totalPages?.encodeToJSON()
        nillableDictionary["created_at"] = self.createdAt?.encodeToJSON()
        nillableDictionary["preview_file"] = self.previewFile
        nillableDictionary["file_url"] = self.fileUrl
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
