//
// InlineResponse2008Files.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class InlineResponse2008Files: JSONEncodable {
    public var id: Int32?
    public var filename: String?
    public var pages: Int32?
    public var size: Int32?
    public var uploaded: ISOFullDate?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id?.encodeToJSON()
        nillableDictionary["filename"] = self.filename
        nillableDictionary["pages"] = self.pages?.encodeToJSON()
        nillableDictionary["size"] = self.size?.encodeToJSON()
        nillableDictionary["uploaded"] = self.uploaded?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
