//
// InlineResponse2003History.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class InlineResponse2003History: JSONEncodable {
    public var id: Int32?
    public var created: InlineResponse2003Created?
    public var documentId: Int32?
    public var document: String?
    public var recipient: String?
    /** The status of the fax job */
    public var status: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id?.encodeToJSON()
        nillableDictionary["created"] = self.created?.encodeToJSON()
        nillableDictionary["document_id"] = self.documentId?.encodeToJSON()
        nillableDictionary["document"] = self.document
        nillableDictionary["recipient"] = self.recipient
        nillableDictionary["status"] = self.status
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
