//
// InlineResponse2002.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class InlineResponse2002: JSONEncodable {
    /** The status of the API request */
    public var status: String?
    /** Display message */
    public var message: String?
    /** Remaining cash balance */
    public var userCashBalance: Double?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["status"] = self.status
        nillableDictionary["message"] = self.message
        nillableDictionary["user_cash_balance"] = self.userCashBalance
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
