//
// FaxReceivingAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



public class FaxReceivingAPI: APIBase {
    /**
     This API gets a list of countries with its area code
     
     - parameter COUNTRY_CODE: (path) Indicates the country code in its ISO 3166-1 alpha-3 format 
     - parameter STATE_ID: (path) The numerical identifier for the state 
     - parameter apiKey: (header)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func areaCodesCountryCodeStateIdGet(COUNTRY_CODE COUNTRY_CODE: Int32, STATE_ID: Int32, apiKey: String, completion: ((data: InlineResponse20014?, error: ErrorType?) -> Void)) {
        areaCodesCountryCodeStateIdGetWithRequestBuilder(COUNTRY_CODE: COUNTRY_CODE, STATE_ID: STATE_ID, apiKey: apiKey).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     This API gets a list of countries with its area code
     - GET /areacodes/{cOUNTRYCODE}/{sTATEID}
     - examples: [{contentType=application/json, example={
  "status" : "status",
  "areacodes" : [ {
    "country_code" : "country_code",
    "area_code" : "area_code",
    "state_id" : 0
  }, {
    "country_code" : "country_code",
    "area_code" : "area_code",
    "state_id" : 0
  } ]
}}, {contentType=application/xml, example=<null>
  <status>aeiou</status>
</null>}]
     - examples: [{contentType=application/json, example={
  "status" : "status",
  "areacodes" : [ {
    "country_code" : "country_code",
    "area_code" : "area_code",
    "state_id" : 0
  }, {
    "country_code" : "country_code",
    "area_code" : "area_code",
    "state_id" : 0
  } ]
}}, {contentType=application/xml, example=<null>
  <status>aeiou</status>
</null>}]
     
     - parameter COUNTRY_CODE: (path) Indicates the country code in its ISO 3166-1 alpha-3 format 
     - parameter STATE_ID: (path) The numerical identifier for the state 
     - parameter apiKey: (header)  

     - returns: RequestBuilder<InlineResponse20014> 
     */
    public class func areaCodesCountryCodeStateIdGetWithRequestBuilder(COUNTRY_CODE COUNTRY_CODE: Int32, STATE_ID: Int32, apiKey: String) -> RequestBuilder<InlineResponse20014> {
        var path = "/areacodes/{cOUNTRYCODE}/{sTATEID}"
        path = path.stringByReplacingOccurrencesOfString("{COUNTRY_CODE}", withString: "\(COUNTRY_CODE)", options: .LiteralSearch, range: nil)
        path = path.stringByReplacingOccurrencesOfString("{STATE_ID}", withString: "\(STATE_ID)", options: .LiteralSearch, range: nil)
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
        let nillableHeaders: [String: AnyObject?] = [
            "api_key": apiKey
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)
 
        let requestBuilder: RequestBuilder<InlineResponse20014>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: true, headers: headerParameters)
    }

    /**
     This API gets a list of DID groups
     
     - parameter COUNTRY_CODE: (path) Indicates the country code of the DID group in its ISO 3166-1 alpha-3 format 
     - parameter areaCode: (query) The area code of the DID group 
     - parameter apiKey: (header)  
     - parameter didGroupIds: (query) Used to display more information about specific DID groups (optional)
     - parameter stateId: (query) The numerical identifier for the didGroup&#39;s state (optional)
     - parameter cityNamePattern: (query) A string pattern for the beginning of city name (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func countriesCountryCodeDidGroupsGet(COUNTRY_CODE COUNTRY_CODE: Int32, areaCode: Int32, apiKey: String, didGroupIds: Int32? = nil, stateId: Int32? = nil, cityNamePattern: Int32? = nil, completion: ((data: InlineResponse20015?, error: ErrorType?) -> Void)) {
        countriesCountryCodeDidGroupsGetWithRequestBuilder(COUNTRY_CODE: COUNTRY_CODE, areaCode: areaCode, apiKey: apiKey, didGroupIds: didGroupIds, stateId: stateId, cityNamePattern: cityNamePattern).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     This API gets a list of DID groups
     - GET /countries/{countryCode}/didgroups
     - examples: [{contentType=application/json, example={
  "data" : [ {
    "city_name" : "city_name",
    "area_code" : "area_code",
    "did_group_id" : 0
  }, {
    "city_name" : "city_name",
    "area_code" : "area_code",
    "did_group_id" : 0
  } ],
  "status" : "status"
}}, {contentType=application/xml, example=<null>
  <status>aeiou</status>
</null>}]
     - examples: [{contentType=application/json, example={
  "data" : [ {
    "city_name" : "city_name",
    "area_code" : "area_code",
    "did_group_id" : 0
  }, {
    "city_name" : "city_name",
    "area_code" : "area_code",
    "did_group_id" : 0
  } ],
  "status" : "status"
}}, {contentType=application/xml, example=<null>
  <status>aeiou</status>
</null>}]
     
     - parameter COUNTRY_CODE: (path) Indicates the country code of the DID group in its ISO 3166-1 alpha-3 format 
     - parameter areaCode: (query) The area code of the DID group 
     - parameter apiKey: (header)  
     - parameter didGroupIds: (query) Used to display more information about specific DID groups (optional)
     - parameter stateId: (query) The numerical identifier for the didGroup&#39;s state (optional)
     - parameter cityNamePattern: (query) A string pattern for the beginning of city name (optional)

     - returns: RequestBuilder<InlineResponse20015> 
     */
    public class func countriesCountryCodeDidGroupsGetWithRequestBuilder(COUNTRY_CODE COUNTRY_CODE: Int32, areaCode: Int32, apiKey: String, didGroupIds: Int32? = nil, stateId: Int32? = nil, cityNamePattern: Int32? = nil) -> RequestBuilder<InlineResponse20015> {
        var path = "/countries/{countryCode}/didgroups"
        path = path.stringByReplacingOccurrencesOfString("{COUNTRY_CODE}", withString: "\(COUNTRY_CODE)", options: .LiteralSearch, range: nil)
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "didGroupIds": didGroupIds?.encodeToJSON(),
            "stateId": stateId?.encodeToJSON(),
            "cityNamePattern": cityNamePattern?.encodeToJSON(),
            "areaCode": areaCode.encodeToJSON()
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
        let nillableHeaders: [String: AnyObject?] = [
            "api_key": apiKey
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)
 
        let requestBuilder: RequestBuilder<InlineResponse20015>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: false, headers: headerParameters)
    }

    /**
     This API gets a list of countries available in the Fax.to coverage
     
     - parameter apiKey: (header)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func countriesGet(apiKey apiKey: String, completion: ((data: InlineResponse20012?, error: ErrorType?) -> Void)) {
        countriesGetWithRequestBuilder(apiKey: apiKey).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     This API gets a list of countries available in the Fax.to coverage
     - GET /countries
     - examples: [{contentType=application/json, example={
  "data" : [ {
    "country" : "country",
    "a2_code" : "a2_code",
    "dial_code" : 0,
    "slug" : "slug"
  }, {
    "country" : "country",
    "a2_code" : "a2_code",
    "dial_code" : 0,
    "slug" : "slug"
  } ],
  "status" : "status"
}}, {contentType=application/xml, example=<null>
  <status>aeiou</status>
</null>}]
     - examples: [{contentType=application/json, example={
  "data" : [ {
    "country" : "country",
    "a2_code" : "a2_code",
    "dial_code" : 0,
    "slug" : "slug"
  }, {
    "country" : "country",
    "a2_code" : "a2_code",
    "dial_code" : 0,
    "slug" : "slug"
  } ],
  "status" : "status"
}}, {contentType=application/xml, example=<null>
  <status>aeiou</status>
</null>}]
     
     - parameter apiKey: (header)  

     - returns: RequestBuilder<InlineResponse20012> 
     */
    public class func countriesGetWithRequestBuilder(apiKey apiKey: String) -> RequestBuilder<InlineResponse20012> {
        let path = "/countries"
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
        let nillableHeaders: [String: AnyObject?] = [
            "api_key": apiKey
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)
 
        let requestBuilder: RequestBuilder<InlineResponse20012>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: true, headers: headerParameters)
    }

    /**
     This API gets a list of incoming faxes
     
     - parameter apiKey: (header)  
     - parameter limit: (query) The number of record to return (optional)
     - parameter page: (query) The page you want to get (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func incomingFaxesGet(apiKey apiKey: String, limit: String? = nil, page: String? = nil, completion: ((data: InlineResponse2004?, error: ErrorType?) -> Void)) {
        incomingFaxesGetWithRequestBuilder(apiKey: apiKey, limit: limit, page: page).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     This API gets a list of incoming faxes
     - GET /incoming-faxes
     - examples: [{contentType=application/json, example={
  "meta" : {
    "pagination" : {
      "per_page" : 2,
      "total" : 5,
      "count" : 5,
      "links" : {
        "next" : "next",
        "previous" : "previous"
      },
      "total_pages" : 9,
      "current_page" : 7
    }
  },
  "inbox" : [ {
    "did_id" : 6,
    "number" : "number",
    "file_url" : "file_url",
    "filename" : "filename",
    "preview_file" : "preview_file",
    "sender" : "sender",
    "created_at" : {
      "date" : "2000-01-23T04:56:07.000+00:00",
      "timezone" : "timezone",
      "timezone_type" : 6
    },
    "id" : 0,
    "filesize" : "filesize",
    "total_pages" : 1
  }, {
    "did_id" : 6,
    "number" : "number",
    "file_url" : "file_url",
    "filename" : "filename",
    "preview_file" : "preview_file",
    "sender" : "sender",
    "created_at" : {
      "date" : "2000-01-23T04:56:07.000+00:00",
      "timezone" : "timezone",
      "timezone_type" : 6
    },
    "id" : 0,
    "filesize" : "filesize",
    "total_pages" : 1
  } ],
  "status" : "status"
}}, {contentType=application/xml, example=<null>
  <status>aeiou</status>
</null>}]
     - examples: [{contentType=application/json, example={
  "meta" : {
    "pagination" : {
      "per_page" : 2,
      "total" : 5,
      "count" : 5,
      "links" : {
        "next" : "next",
        "previous" : "previous"
      },
      "total_pages" : 9,
      "current_page" : 7
    }
  },
  "inbox" : [ {
    "did_id" : 6,
    "number" : "number",
    "file_url" : "file_url",
    "filename" : "filename",
    "preview_file" : "preview_file",
    "sender" : "sender",
    "created_at" : {
      "date" : "2000-01-23T04:56:07.000+00:00",
      "timezone" : "timezone",
      "timezone_type" : 6
    },
    "id" : 0,
    "filesize" : "filesize",
    "total_pages" : 1
  }, {
    "did_id" : 6,
    "number" : "number",
    "file_url" : "file_url",
    "filename" : "filename",
    "preview_file" : "preview_file",
    "sender" : "sender",
    "created_at" : {
      "date" : "2000-01-23T04:56:07.000+00:00",
      "timezone" : "timezone",
      "timezone_type" : 6
    },
    "id" : 0,
    "filesize" : "filesize",
    "total_pages" : 1
  } ],
  "status" : "status"
}}, {contentType=application/xml, example=<null>
  <status>aeiou</status>
</null>}]
     
     - parameter apiKey: (header)  
     - parameter limit: (query) The number of record to return (optional)
     - parameter page: (query) The page you want to get (optional)

     - returns: RequestBuilder<InlineResponse2004> 
     */
    public class func incomingFaxesGetWithRequestBuilder(apiKey apiKey: String, limit: String? = nil, page: String? = nil) -> RequestBuilder<InlineResponse2004> {
        let path = "/incoming-faxes"
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "limit": limit,
            "page": page
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
        let nillableHeaders: [String: AnyObject?] = [
            "api_key": apiKey
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)
 
        let requestBuilder: RequestBuilder<InlineResponse2004>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: false, headers: headerParameters)
    }

    /**
     This API gets a list of incoming faxes for a specific recipient
     
     - parameter recipient: (path) The recipient&#39;s fax number 
     - parameter apiKey: (header)  
     - parameter limit: (query) The number of record to return (optional)
     - parameter page: (query) The page you want to get (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func incomingFaxesRecipientGet(recipient recipient: Int32, apiKey: String, limit: String? = nil, page: String? = nil, completion: ((data: InlineResponse2004?, error: ErrorType?) -> Void)) {
        incomingFaxesRecipientGetWithRequestBuilder(recipient: recipient, apiKey: apiKey, limit: limit, page: page).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     This API gets a list of incoming faxes for a specific recipient
     - GET /incoming-faxes/{recipient}
     - examples: [{contentType=application/json, example={
  "meta" : {
    "pagination" : {
      "per_page" : 2,
      "total" : 5,
      "count" : 5,
      "links" : {
        "next" : "next",
        "previous" : "previous"
      },
      "total_pages" : 9,
      "current_page" : 7
    }
  },
  "inbox" : [ {
    "did_id" : 6,
    "number" : "number",
    "file_url" : "file_url",
    "filename" : "filename",
    "preview_file" : "preview_file",
    "sender" : "sender",
    "created_at" : {
      "date" : "2000-01-23T04:56:07.000+00:00",
      "timezone" : "timezone",
      "timezone_type" : 6
    },
    "id" : 0,
    "filesize" : "filesize",
    "total_pages" : 1
  }, {
    "did_id" : 6,
    "number" : "number",
    "file_url" : "file_url",
    "filename" : "filename",
    "preview_file" : "preview_file",
    "sender" : "sender",
    "created_at" : {
      "date" : "2000-01-23T04:56:07.000+00:00",
      "timezone" : "timezone",
      "timezone_type" : 6
    },
    "id" : 0,
    "filesize" : "filesize",
    "total_pages" : 1
  } ],
  "status" : "status"
}}, {contentType=application/xml, example=<null>
  <status>aeiou</status>
</null>}]
     - examples: [{contentType=application/json, example={
  "meta" : {
    "pagination" : {
      "per_page" : 2,
      "total" : 5,
      "count" : 5,
      "links" : {
        "next" : "next",
        "previous" : "previous"
      },
      "total_pages" : 9,
      "current_page" : 7
    }
  },
  "inbox" : [ {
    "did_id" : 6,
    "number" : "number",
    "file_url" : "file_url",
    "filename" : "filename",
    "preview_file" : "preview_file",
    "sender" : "sender",
    "created_at" : {
      "date" : "2000-01-23T04:56:07.000+00:00",
      "timezone" : "timezone",
      "timezone_type" : 6
    },
    "id" : 0,
    "filesize" : "filesize",
    "total_pages" : 1
  }, {
    "did_id" : 6,
    "number" : "number",
    "file_url" : "file_url",
    "filename" : "filename",
    "preview_file" : "preview_file",
    "sender" : "sender",
    "created_at" : {
      "date" : "2000-01-23T04:56:07.000+00:00",
      "timezone" : "timezone",
      "timezone_type" : 6
    },
    "id" : 0,
    "filesize" : "filesize",
    "total_pages" : 1
  } ],
  "status" : "status"
}}, {contentType=application/xml, example=<null>
  <status>aeiou</status>
</null>}]
     
     - parameter recipient: (path) The recipient&#39;s fax number 
     - parameter apiKey: (header)  
     - parameter limit: (query) The number of record to return (optional)
     - parameter page: (query) The page you want to get (optional)

     - returns: RequestBuilder<InlineResponse2004> 
     */
    public class func incomingFaxesRecipientGetWithRequestBuilder(recipient recipient: Int32, apiKey: String, limit: String? = nil, page: String? = nil) -> RequestBuilder<InlineResponse2004> {
        var path = "/incoming-faxes/{recipient}"
        path = path.stringByReplacingOccurrencesOfString("{recipient}", withString: "\(recipient)", options: .LiteralSearch, range: nil)
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "limit": limit,
            "page": page
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
        let nillableHeaders: [String: AnyObject?] = [
            "api_key": apiKey
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)
 
        let requestBuilder: RequestBuilder<InlineResponse2004>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: false, headers: headerParameters)
    }

    /**
     This API gets a list of numbers to get the current configuration of one or multiple number
     
     - parameter apiKey: (header)  
     - parameter limit: (query) The number of record to return (optional)
     - parameter page: (query) The page you want to get (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func numbersGet(apiKey apiKey: String, limit: String? = nil, page: String? = nil, completion: ((data: InlineResponse20017?, error: ErrorType?) -> Void)) {
        numbersGetWithRequestBuilder(apiKey: apiKey, limit: limit, page: page).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     This API gets a list of numbers to get the current configuration of one or multiple number
     - GET /numbers
     - examples: [{contentType=application/json, example={
  "meta" : {
    "pagination" : {
      "per_page" : 2,
      "total" : 5,
      "count" : 5,
      "links" : {
        "next" : "next",
        "previous" : "previous"
      },
      "total_pages" : 9,
      "current_page" : 7
    }
  },
  "numbers" : [ {
    "country_code" : "country_code",
    "country" : "country",
    "city_name" : "city_name",
    "order_reference" : "order_reference",
    "area_code" : "area_code",
    "did_number" : "did_number",
    "id" : 0,
    "expiration_date" : "2000-01-23",
    "did_group_id" : 6,
    "status" : "status"
  }, {
    "country_code" : "country_code",
    "country" : "country",
    "city_name" : "city_name",
    "order_reference" : "order_reference",
    "area_code" : "area_code",
    "did_number" : "did_number",
    "id" : 0,
    "expiration_date" : "2000-01-23",
    "did_group_id" : 6,
    "status" : "status"
  } ],
  "status" : "status"
}}, {contentType=application/xml, example=<null>
  <status>aeiou</status>
</null>}]
     - examples: [{contentType=application/json, example={
  "meta" : {
    "pagination" : {
      "per_page" : 2,
      "total" : 5,
      "count" : 5,
      "links" : {
        "next" : "next",
        "previous" : "previous"
      },
      "total_pages" : 9,
      "current_page" : 7
    }
  },
  "numbers" : [ {
    "country_code" : "country_code",
    "country" : "country",
    "city_name" : "city_name",
    "order_reference" : "order_reference",
    "area_code" : "area_code",
    "did_number" : "did_number",
    "id" : 0,
    "expiration_date" : "2000-01-23",
    "did_group_id" : 6,
    "status" : "status"
  }, {
    "country_code" : "country_code",
    "country" : "country",
    "city_name" : "city_name",
    "order_reference" : "order_reference",
    "area_code" : "area_code",
    "did_number" : "did_number",
    "id" : 0,
    "expiration_date" : "2000-01-23",
    "did_group_id" : 6,
    "status" : "status"
  } ],
  "status" : "status"
}}, {contentType=application/xml, example=<null>
  <status>aeiou</status>
</null>}]
     
     - parameter apiKey: (header)  
     - parameter limit: (query) The number of record to return (optional)
     - parameter page: (query) The page you want to get (optional)

     - returns: RequestBuilder<InlineResponse20017> 
     */
    public class func numbersGetWithRequestBuilder(apiKey apiKey: String, limit: String? = nil, page: String? = nil) -> RequestBuilder<InlineResponse20017> {
        let path = "/numbers"
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "limit": limit,
            "page": page
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
        let nillableHeaders: [String: AnyObject?] = [
            "api_key": apiKey
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)
 
        let requestBuilder: RequestBuilder<InlineResponse20017>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: false, headers: headerParameters)
    }

    /**
     This API gets a list of provisioned numbers
     
     - parameter didGroupId: (query) The id of the did group 
     - parameter apiKey: (header)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func provisionNumbersGet(didGroupId didGroupId: Int32, apiKey: String, completion: ((data: InlineResponse20016?, error: ErrorType?) -> Void)) {
        provisionNumbersGetWithRequestBuilder(didGroupId: didGroupId, apiKey: apiKey).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     This API gets a list of provisioned numbers
     - GET /countries/didgroups/{didGroupId}/provision
     - examples: [{contentType=application/json, example={
  "data" : {
    "did_id" : 6,
    "country_code" : "country_code",
    "number" : "number",
    "city_name" : "city_name",
    "trunk_id" : 5,
    "area_code" : "area_code",
    "id" : 0,
    "type" : "type",
    "did_group_id" : 1
  },
  "message" : "message",
  "status" : "status"
}}, {contentType=application/xml, example=<null>
  <status>aeiou</status>
  <message>aeiou</message>
</null>}]
     - examples: [{contentType=application/json, example={
  "data" : {
    "did_id" : 6,
    "country_code" : "country_code",
    "number" : "number",
    "city_name" : "city_name",
    "trunk_id" : 5,
    "area_code" : "area_code",
    "id" : 0,
    "type" : "type",
    "did_group_id" : 1
  },
  "message" : "message",
  "status" : "status"
}}, {contentType=application/xml, example=<null>
  <status>aeiou</status>
  <message>aeiou</message>
</null>}]
     
     - parameter didGroupId: (query) The id of the did group 
     - parameter apiKey: (header)  

     - returns: RequestBuilder<InlineResponse20016> 
     */
    public class func provisionNumbersGetWithRequestBuilder(didGroupId didGroupId: Int32, apiKey: String) -> RequestBuilder<InlineResponse20016> {
        let path = "/countries/didgroups/{didGroupId}/provision"
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "did_group_id": didGroupId.encodeToJSON()
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
        let nillableHeaders: [String: AnyObject?] = [
            "api_key": apiKey
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)
 
        let requestBuilder: RequestBuilder<InlineResponse20016>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: false, headers: headerParameters)
    }

    /**
     This API gets a list of states of a given country available in the Fax.to coverage
     
     - parameter COUNTRY_CODE: (path) Indicates the country code in its ISO 3166-1 alpha-3 format 
     - parameter apiKey: (header)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func statesCountryCodeGet(COUNTRY_CODE COUNTRY_CODE: Int32, apiKey: String, completion: ((data: InlineResponse20013?, error: ErrorType?) -> Void)) {
        statesCountryCodeGetWithRequestBuilder(COUNTRY_CODE: COUNTRY_CODE, apiKey: apiKey).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     This API gets a list of states of a given country available in the Fax.to coverage
     - GET /states/{cOUNTRYCODE}
     - examples: [{contentType=application/json, example={
  "status" : "status",
  "states" : [ {
    "code" : "code",
    "name" : "name",
    "id" : "id"
  }, {
    "code" : "code",
    "name" : "name",
    "id" : "id"
  } ]
}}, {contentType=application/xml, example=<null>
  <status>aeiou</status>
</null>}]
     - examples: [{contentType=application/json, example={
  "status" : "status",
  "states" : [ {
    "code" : "code",
    "name" : "name",
    "id" : "id"
  }, {
    "code" : "code",
    "name" : "name",
    "id" : "id"
  } ]
}}, {contentType=application/xml, example=<null>
  <status>aeiou</status>
</null>}]
     
     - parameter COUNTRY_CODE: (path) Indicates the country code in its ISO 3166-1 alpha-3 format 
     - parameter apiKey: (header)  

     - returns: RequestBuilder<InlineResponse20013> 
     */
    public class func statesCountryCodeGetWithRequestBuilder(COUNTRY_CODE COUNTRY_CODE: Int32, apiKey: String) -> RequestBuilder<InlineResponse20013> {
        var path = "/states/{cOUNTRYCODE}"
        path = path.stringByReplacingOccurrencesOfString("{COUNTRY_CODE}", withString: "\(COUNTRY_CODE)", options: .LiteralSearch, range: nil)
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
        let nillableHeaders: [String: AnyObject?] = [
            "api_key": apiKey
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)
 
        let requestBuilder: RequestBuilder<InlineResponse20013>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: true, headers: headerParameters)
    }

}
