//
// FaxSendingAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



public class FaxSendingAPI: APIBase {
    /**
     This API is for computing the cost of the fax to be sent
     
     - parameter documentId: (path) The id of the document to be sent 
     - parameter apiKey: (header)  
     - parameter faxNumber: (query) The fax number of the recipient (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func faxDocumentIdCostsGet(documentId documentId: Int32, apiKey: String, faxNumber: String? = nil, completion: ((data: InlineResponse2001?, error: ErrorType?) -> Void)) {
        faxDocumentIdCostsGetWithRequestBuilder(documentId: documentId, apiKey: apiKey, faxNumber: faxNumber).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     This API is for computing the cost of the fax to be sent
     - GET /fax/{documentId}/costs
     - examples: [{contentType=application/json, example={
  "cost" : 0.80082819046101150206595775671303272247314453125,
  "status" : "status"
}}, {contentType=application/xml, example=<null>
  <status>aeiou</status>
  <cost>1.3579</cost>
</null>}]
     - examples: [{contentType=application/json, example={
  "cost" : 0.80082819046101150206595775671303272247314453125,
  "status" : "status"
}}, {contentType=application/xml, example=<null>
  <status>aeiou</status>
  <cost>1.3579</cost>
</null>}]
     
     - parameter documentId: (path) The id of the document to be sent 
     - parameter apiKey: (header)  
     - parameter faxNumber: (query) The fax number of the recipient (optional)

     - returns: RequestBuilder<InlineResponse2001> 
     */
    public class func faxDocumentIdCostsGetWithRequestBuilder(documentId documentId: Int32, apiKey: String, faxNumber: String? = nil) -> RequestBuilder<InlineResponse2001> {
        var path = "/fax/{documentId}/costs"
        path = path.stringByReplacingOccurrencesOfString("{document_id}", withString: "\(documentId)", options: .LiteralSearch, range: nil)
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "fax_number": faxNumber
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
        let nillableHeaders: [String: AnyObject?] = [
            "api_key": apiKey
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)
 
        let requestBuilder: RequestBuilder<InlineResponse2001>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: false, headers: headerParameters)
    }

    /**
     This API gets the history of a fax
     
     - parameter apiKey: (header)  
     - parameter limit: (query) The number of record to return (optional)
     - parameter page: (query) The page you want to get (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func faxHistoryGet(apiKey apiKey: String, limit: String? = nil, page: String? = nil, completion: ((data: InlineResponse2003?, error: ErrorType?) -> Void)) {
        faxHistoryGetWithRequestBuilder(apiKey: apiKey, limit: limit, page: page).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     This API gets the history of a fax
     - GET /fax-history
     - examples: [{contentType=application/json, example={
  "history" : [ {
    "created" : {
      "date" : "2000-01-23T04:56:07.000+00:00",
      "timezone" : "timezone",
      "timezone_type" : 6
    },
    "document" : "document",
    "recipient" : "recipient",
    "id" : 0,
    "document_id" : 1,
    "status" : "status"
  }, {
    "created" : {
      "date" : "2000-01-23T04:56:07.000+00:00",
      "timezone" : "timezone",
      "timezone_type" : 6
    },
    "document" : "document",
    "recipient" : "recipient",
    "id" : 0,
    "document_id" : 1,
    "status" : "status"
  } ],
  "status" : "status"
}}, {contentType=application/xml, example=<null>
  <status>aeiou</status>
</null>}]
     - examples: [{contentType=application/json, example={
  "history" : [ {
    "created" : {
      "date" : "2000-01-23T04:56:07.000+00:00",
      "timezone" : "timezone",
      "timezone_type" : 6
    },
    "document" : "document",
    "recipient" : "recipient",
    "id" : 0,
    "document_id" : 1,
    "status" : "status"
  }, {
    "created" : {
      "date" : "2000-01-23T04:56:07.000+00:00",
      "timezone" : "timezone",
      "timezone_type" : 6
    },
    "document" : "document",
    "recipient" : "recipient",
    "id" : 0,
    "document_id" : 1,
    "status" : "status"
  } ],
  "status" : "status"
}}, {contentType=application/xml, example=<null>
  <status>aeiou</status>
</null>}]
     
     - parameter apiKey: (header)  
     - parameter limit: (query) The number of record to return (optional)
     - parameter page: (query) The page you want to get (optional)

     - returns: RequestBuilder<InlineResponse2003> 
     */
    public class func faxHistoryGetWithRequestBuilder(apiKey apiKey: String, limit: String? = nil, page: String? = nil) -> RequestBuilder<InlineResponse2003> {
        let path = "/fax-history"
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "limit": limit,
            "page": page
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
        let nillableHeaders: [String: AnyObject?] = [
            "api_key": apiKey
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)
 
        let requestBuilder: RequestBuilder<InlineResponse2003>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: false, headers: headerParameters)
    }

    /**
     This API gets the status of a fax
     
     - parameter faxJobId: (path) The id of the fax job 
     - parameter apiKey: (header)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func faxJobIdStatusGet(faxJobId faxJobId: Int32, apiKey: String, completion: ((data: InlineResponse2002?, error: ErrorType?) -> Void)) {
        faxJobIdStatusGetWithRequestBuilder(faxJobId: faxJobId, apiKey: apiKey).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     This API gets the status of a fax
     - GET /fax/{faxJobId}/status
     - examples: [{contentType=application/json, example={
  "message" : "message",
  "user_cash_balance" : 0.80082819046101150206595775671303272247314453125,
  "status" : "status"
}}, {contentType=application/xml, example=<null>
  <status>aeiou</status>
  <message>aeiou</message>
  <user_cash_balance>1.3579</user_cash_balance>
</null>}]
     - examples: [{contentType=application/json, example={
  "message" : "message",
  "user_cash_balance" : 0.80082819046101150206595775671303272247314453125,
  "status" : "status"
}}, {contentType=application/xml, example=<null>
  <status>aeiou</status>
  <message>aeiou</message>
  <user_cash_balance>1.3579</user_cash_balance>
</null>}]
     
     - parameter faxJobId: (path) The id of the fax job 
     - parameter apiKey: (header)  

     - returns: RequestBuilder<InlineResponse2002> 
     */
    public class func faxJobIdStatusGetWithRequestBuilder(faxJobId faxJobId: Int32, apiKey: String) -> RequestBuilder<InlineResponse2002> {
        var path = "/fax/{faxJobId}/status"
        path = path.stringByReplacingOccurrencesOfString("{fax_job_id}", withString: "\(faxJobId)", options: .LiteralSearch, range: nil)
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
        let nillableHeaders: [String: AnyObject?] = [
            "api_key": apiKey
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)
 
        let requestBuilder: RequestBuilder<InlineResponse2002>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: true, headers: headerParameters)
    }

    /**
     This API is for sending a new fax in any fax numbers anywhere in the world
     
     - parameter faxNumber: (body) The fax number of the recipient 
     - parameter documentId: (body) The id of the document to be sent 
     - parameter apiKey: (header)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func faxPost(faxNumber faxNumber: , documentId: , apiKey: String, completion: ((data: InlineResponse200?, error: ErrorType?) -> Void)) {
        faxPostWithRequestBuilder(faxNumber: faxNumber, documentId: documentId, apiKey: apiKey).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     This API is for sending a new fax in any fax numbers anywhere in the world
     - POST /fax
     - examples: [{contentType=application/json, example={
  "cost" : 1.46581298050294517310021547018550336360931396484375,
  "fax_job_id" : 0,
  "user_cash_balance" : 6.02745618307040320615897144307382404804229736328125,
  "status" : "status"
}}, {contentType=application/xml, example=<null>
  <status>aeiou</status>
  <fax_job_id>123</fax_job_id>
  <user_cash_balance>1.3579</user_cash_balance>
  <cost>1.3579</cost>
</null>}]
     - examples: [{contentType=application/json, example={
  "cost" : 1.46581298050294517310021547018550336360931396484375,
  "fax_job_id" : 0,
  "user_cash_balance" : 6.02745618307040320615897144307382404804229736328125,
  "status" : "status"
}}, {contentType=application/xml, example=<null>
  <status>aeiou</status>
  <fax_job_id>123</fax_job_id>
  <user_cash_balance>1.3579</user_cash_balance>
  <cost>1.3579</cost>
</null>}]
     
     - parameter faxNumber: (body) The fax number of the recipient 
     - parameter documentId: (body) The id of the document to be sent 
     - parameter apiKey: (header)  

     - returns: RequestBuilder<InlineResponse200> 
     */
    public class func faxPostWithRequestBuilder(faxNumber faxNumber: , documentId: , apiKey: String) -> RequestBuilder<InlineResponse200> {
        let path = "/fax"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = documentId.encodeToJSON() as? [String:AnyObject]
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
        let nillableHeaders: [String: AnyObject?] = [
            "api_key": apiKey
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)
 
        let requestBuilder: RequestBuilder<InlineResponse200>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: convertedParameters, isBody: true, headers: headerParameters)
    }

    /**
     This API is used for cleaning a document
     
     - parameter documentId: (header) The id of the document 
     - parameter apiKey: (header)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func fileCleanGet(documentId documentId: Int32, apiKey: String, completion: ((data: InlineResponse2009?, error: ErrorType?) -> Void)) {
        fileCleanGetWithRequestBuilder(documentId: documentId, apiKey: apiKey).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     This API is used for cleaning a document
     - GET /file-clean
     - examples: [{contentType=application/json, example={
  "s3" : 5,
  "preview_image" : "preview_image",
  "filesize" : "filesize",
  "total_pages" : 7,
  "preview_in_storage" : 1,
  "filename" : "filename",
  "preview_file" : "preview_file",
  "updated_at" : "2000-01-23T04:56:07.000+00:00",
  "user_id" : 0,
  "team_user_id" : 2,
  "file_extension" : "file_extension",
  "created_date" : "2000-01-23T04:56:07.000+00:00",
  "id" : 6,
  "orig_filename" : "orig_filename",
  "server_document_id" : 5,
  "status" : "status",
  "filename_uploaded" : "filename_uploaded"
}}, {contentType=application/xml, example=<null>
  <status>aeiou</status>
  <user_id>123</user_id>
  <created_date>2000-01-23T04:56:07.000Z</created_date>
  <id>123</id>
  <filename>aeiou</filename>
  <orig_filename>aeiou</orig_filename>
  <preview_file>aeiou</preview_file>
  <preview_image>aeiou</preview_image>
  <preview_in_storage>123</preview_in_storage>
  <file_extension>aeiou</file_extension>
  <filename_uploaded>aeiou</filename_uploaded>
  <filesize>aeiou</filesize>
  <s3>123</s3>
  <server_document_id>123</server_document_id>
  <team_user_id>123</team_user_id>
  <total_pages>123</total_pages>
  <updated_at>2000-01-23T04:56:07.000Z</updated_at>
</null>}]
     - examples: [{contentType=application/json, example={
  "s3" : 5,
  "preview_image" : "preview_image",
  "filesize" : "filesize",
  "total_pages" : 7,
  "preview_in_storage" : 1,
  "filename" : "filename",
  "preview_file" : "preview_file",
  "updated_at" : "2000-01-23T04:56:07.000+00:00",
  "user_id" : 0,
  "team_user_id" : 2,
  "file_extension" : "file_extension",
  "created_date" : "2000-01-23T04:56:07.000+00:00",
  "id" : 6,
  "orig_filename" : "orig_filename",
  "server_document_id" : 5,
  "status" : "status",
  "filename_uploaded" : "filename_uploaded"
}}, {contentType=application/xml, example=<null>
  <status>aeiou</status>
  <user_id>123</user_id>
  <created_date>2000-01-23T04:56:07.000Z</created_date>
  <id>123</id>
  <filename>aeiou</filename>
  <orig_filename>aeiou</orig_filename>
  <preview_file>aeiou</preview_file>
  <preview_image>aeiou</preview_image>
  <preview_in_storage>123</preview_in_storage>
  <file_extension>aeiou</file_extension>
  <filename_uploaded>aeiou</filename_uploaded>
  <filesize>aeiou</filesize>
  <s3>123</s3>
  <server_document_id>123</server_document_id>
  <team_user_id>123</team_user_id>
  <total_pages>123</total_pages>
  <updated_at>2000-01-23T04:56:07.000Z</updated_at>
</null>}]
     
     - parameter documentId: (header) The id of the document 
     - parameter apiKey: (header)  

     - returns: RequestBuilder<InlineResponse2009> 
     */
    public class func fileCleanGetWithRequestBuilder(documentId documentId: Int32, apiKey: String) -> RequestBuilder<InlineResponse2009> {
        let path = "/file-clean"
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
        let nillableHeaders: [String: AnyObject?] = [
            "document_id": documentId.encodeToJSON(),
            "api_key": apiKey
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)
 
        let requestBuilder: RequestBuilder<InlineResponse2009>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: true, headers: headerParameters)
    }

    /**
     This API generates a preview of a document
     
     - parameter documentId: (header) The id of the document 
     - parameter apiKey: (header)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func fileGeneratePreviewGet(documentId documentId: Int32, apiKey: String, completion: ((data: InlineResponse20010?, error: ErrorType?) -> Void)) {
        fileGeneratePreviewGetWithRequestBuilder(documentId: documentId, apiKey: apiKey).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     This API generates a preview of a document
     - GET /file-generate-preview
     - examples: [{contentType=application/json, example={
  "url" : "url",
  "status" : "status"
}}, {contentType=application/xml, example=<null>
  <status>aeiou</status>
  <url>aeiou</url>
</null>}]
     - examples: [{contentType=application/json, example={
  "url" : "url",
  "status" : "status"
}}, {contentType=application/xml, example=<null>
  <status>aeiou</status>
  <url>aeiou</url>
</null>}]
     
     - parameter documentId: (header) The id of the document 
     - parameter apiKey: (header)  

     - returns: RequestBuilder<InlineResponse20010> 
     */
    public class func fileGeneratePreviewGetWithRequestBuilder(documentId documentId: Int32, apiKey: String) -> RequestBuilder<InlineResponse20010> {
        let path = "/file-generate-preview"
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
        let nillableHeaders: [String: AnyObject?] = [
            "document_id": documentId.encodeToJSON(),
            "api_key": apiKey
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)
 
        let requestBuilder: RequestBuilder<InlineResponse20010>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: true, headers: headerParameters)
    }

    /**
     This API deletes a document
     
     - parameter documentId: (path) The id of the document 
     - parameter apiKey: (header)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func filesDocumentIDDelete(documentId documentId: Int32, apiKey: String, completion: ((data: InlineResponse20011?, error: ErrorType?) -> Void)) {
        filesDocumentIDDeleteWithRequestBuilder(documentId: documentId, apiKey: apiKey).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     This API deletes a document
     - DELETE /files/{documentId}
     - examples: [{contentType=application/json, example={
  "status" : "status"
}}, {contentType=application/xml, example=<null>
  <status>aeiou</status>
</null>}]
     - examples: [{contentType=application/json, example={
  "status" : "status"
}}, {contentType=application/xml, example=<null>
  <status>aeiou</status>
</null>}]
     
     - parameter documentId: (path) The id of the document 
     - parameter apiKey: (header)  

     - returns: RequestBuilder<InlineResponse20011> 
     */
    public class func filesDocumentIDDeleteWithRequestBuilder(documentId documentId: Int32, apiKey: String) -> RequestBuilder<InlineResponse20011> {
        var path = "/files/{documentId}"
        path = path.stringByReplacingOccurrencesOfString("{document_id}", withString: "\(documentId)", options: .LiteralSearch, range: nil)
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
        let nillableHeaders: [String: AnyObject?] = [
            "api_key": apiKey
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)
 
        let requestBuilder: RequestBuilder<InlineResponse20011>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "DELETE", URLString: URLString, parameters: convertedParameters, isBody: true, headers: headerParameters)
    }

    /**
     This API gets all the files of a certain user
     
     - parameter apiKey: (header)  
     - parameter limit: (query) The number of record to return (optional)
     - parameter page: (query) The page you want to get (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func filesGet(apiKey apiKey: String, limit: String? = nil, page: String? = nil, completion: ((data: InlineResponse2008?, error: ErrorType?) -> Void)) {
        filesGetWithRequestBuilder(apiKey: apiKey, limit: limit, page: page).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     This API gets all the files of a certain user
     - GET /files
     - examples: [{contentType=application/json, example={
  "files" : [ {
    "filename" : "filename",
    "pages" : 6,
    "size" : 1,
    "uploaded" : "2000-01-23",
    "id" : 0
  }, {
    "filename" : "filename",
    "pages" : 6,
    "size" : 1,
    "uploaded" : "2000-01-23",
    "id" : 0
  } ],
  "status" : "status"
}}, {contentType=application/xml, example=<null>
  <status>aeiou</status>
</null>}]
     - examples: [{contentType=application/json, example={
  "files" : [ {
    "filename" : "filename",
    "pages" : 6,
    "size" : 1,
    "uploaded" : "2000-01-23",
    "id" : 0
  }, {
    "filename" : "filename",
    "pages" : 6,
    "size" : 1,
    "uploaded" : "2000-01-23",
    "id" : 0
  } ],
  "status" : "status"
}}, {contentType=application/xml, example=<null>
  <status>aeiou</status>
</null>}]
     
     - parameter apiKey: (header)  
     - parameter limit: (query) The number of record to return (optional)
     - parameter page: (query) The page you want to get (optional)

     - returns: RequestBuilder<InlineResponse2008> 
     */
    public class func filesGetWithRequestBuilder(apiKey apiKey: String, limit: String? = nil, page: String? = nil) -> RequestBuilder<InlineResponse2008> {
        let path = "/files"
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "limit": limit,
            "page": page
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
        let nillableHeaders: [String: AnyObject?] = [
            "api_key": apiKey
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)
 
        let requestBuilder: RequestBuilder<InlineResponse2008>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: false, headers: headerParameters)
    }

}
