//
// UserAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



public class UserAPI: APIBase {
    /**
     This API gets the balance of a user account
     
     - parameter apiKey: (header)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func balanceGet(apiKey apiKey: String, completion: ((data: InlineResponse2007?, error: ErrorType?) -> Void)) {
        balanceGetWithRequestBuilder(apiKey: apiKey).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     This API gets the balance of a user account
     - GET /balance
     - examples: [{contentType=application/json, example={
  "balance" : 0.80082819046101150206595775671303272247314453125,
  "status" : "status"
}}, {contentType=application/xml, example=<null>
  <status>aeiou</status>
  <balance>1.3579</balance>
</null>}]
     - examples: [{contentType=application/json, example={
  "balance" : 0.80082819046101150206595775671303272247314453125,
  "status" : "status"
}}, {contentType=application/xml, example=<null>
  <status>aeiou</status>
  <balance>1.3579</balance>
</null>}]
     
     - parameter apiKey: (header)  

     - returns: RequestBuilder<InlineResponse2007> 
     */
    public class func balanceGetWithRequestBuilder(apiKey apiKey: String) -> RequestBuilder<InlineResponse2007> {
        let path = "/balance"
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
        let nillableHeaders: [String: AnyObject?] = [
            "api_key": apiKey
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)
 
        let requestBuilder: RequestBuilder<InlineResponse2007>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: true, headers: headerParameters)
    }

}
